### ISSUE TITLE
Investigate Spherical Harmonics?

### ISSUE THREAD

**Issue by n8xm** [n8vm/BSDF-Visualizer#26]
Do we want a noise-free visualizer? (Might look good in a side-by-side comparison against Disney's tool.) Do we want to showcase realtime techniques? If we want to do those things we should investigate SH. 

References:
1. [Stupid Spherical Harmonics Tricks, PP Sloan, 2008](http://www.ppsloan.org/publications/StupidSH36.pdf)
2. [Unreal Engine SIGGRAPH talk, 2013](https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf) 
3.  [An Efficient Representation for Irradiance Environment Maps, Ramamoorthi and Hanrahan, 2001](https://cseweb.ucsd.edu/~ravir/papers/envmap/envmap.pdf)

**Comment by n8vm** [comment]
SH may be difficult to implement for arbitrary BRDFs, especially BRDFs which are anisotropic around a sampling hemisphere.

I personally want a chance to implement SH at some point, but this project might not be the one to do it. So for the time being, I'm going to suggest we add SH as an optional deliverable, which we can work on if we get some extra time.
