### ISSUE TITLE
Add ability to change light intensity using slider

### ISSUE THREAD

**Issue by n8vm** [n8vm/BSDF-Visualizer#34]
Some shaders, like ashikhman_shirley appear very dark with just a point light. Might be nice to be able to change light intensity.

**Comment by n8xm** [comment]
I agree. In addition to changing light intensity, I'm playing with a heatmap view (see picture below, which uses the "Jet" colormap), which should make intensity changes easier to see. I hope that's okay. 
![teapot_heatmap](https://user-images.githubusercontent.com/5407450/37846772-e82ed588-2e8b-11e8-885c-7c3de674b9b9.png)

**Comment by n8vm** [comment]
That could be helpful, although I wouldn’t want jet to be the default. We could add a color map selection on the bottom or something

**Comment by n8xm** [comment]
> I wouldn’t want jet to be the default. We could add a color map selection on the bottom or something.

That's exactly what I was thinking.
