### ISSUE TITLE
Sliders "shake" when printed values change in width

### ISSUE THREAD

**Issue by n8xm** [n8vm/BSDF-Visualizer#6]
Right now when our slider values transition between single-digit and double-digit values, there is no formatted print so it changes the location of the next slider, which causes jittering. We should be able to fix it using string formatting, or by putting sliders in separate rows.

**Comment by n8vm** [comment]
With the newer sliders, I've been removing the output number, since I'm not so sure it's a necessary thing to show. That effectively solves the problem.
